name: auto-translate

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

permissions:
  contents: write  # Needed to commit back to repo

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Stable version

      # 3. Disable any proxy to avoid OpenAI errors
      - name: Disable proxies
        run: |
          unset HTTP_PROXY
          unset HTTPS_PROXY
          unset http_proxy
          unset https_proxy

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --no-cache-dir

      # 5. Provide OpenAI API key
      - name: Set OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV

      # 6. Run translation script
      - name: Run translation
        run: python tools/translate_to_en_openai.py

      # 7. Commit & push translated files
      - name: Commit & Push translations
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.en.md
          git commit -m "Auto-translate DE → EN via OpenAI" || echo "No changes to commit"
          git push
