name: auto-translate

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade openai>=1.0.0 --no-cache-dir
          pip install -r requirements.txt

      - name: Disable proxies to avoid OpenAI error
        run: |
          unset HTTP_PROXY
          unset HTTPS_PROXY

      # 4. Set OpenAI API Key
      - name: Set OpenAI API Key
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
      - name: Check OpenAI version
        run: python -m pip show openai


      # 5. Run translation script
      - name: Run translation
        run: python tools/translate_to_en_openai.py

      # 6. Commit & push translated files
      - name: Commit & Push translations
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/*.en.md
          git commit -m "Auto-translate DE → EN via OpenAI" || echo "No changes to commit"
          git push





